### PR TITLE
Integrate Mayhem

### PR DESCRIPTION
**Pull request by rnshah9**

### CODE REVIEW

**Comment by rnshah9** [comment]
I'm not sure why adding a package stage causes Mayhem to [fail](https://github.com/rnshah9/mayhem-szl/actions/runs/2466051576). Should I revert it?

**Review by xansec — APPROVED** [review]
LGTM!

**Comment by xansec** [comment]
I somehow missed that this was failing (latest run on your own account seems to be successful). I'm not sure either, but running locally doesn't show any problems. I'll look into this.

**Comment by rnshah9** [comment]
I also missed this. Strange - the run completes 56 test cases _then_ fails.

I tried removing the package stage and it works fine. Let me know if there's anything more I should do.

**Comment by xansec** [comment]
Should be fine - https://github.com/mayhemheroes/szl/pull/2 succeeded so I think we're good here.

**Pull request merged**
